### ISSUE TITLE
Ouverture de l'explorateur de dossier sur windows 10

### ISSUE THREAD

**Issue by Corax89x** [Thomas-Lecuppre/RevitCleaner#2]
Bug empêchant l'ouverture de l'arborescence de sélection de dossier sur Windows 10 22H1
![image_2023-03-23_130109845](https://user-images.githubusercontent.com/75851929/227197668-274f212e-12b4-4b0b-86ff-a0e91658978b.png)

**Comment by Thomas-Lecuppre** [comment]
Problème fixé pour la 3.1.2 qui sera déployée dans la soirée.
